# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.component import Child, Component

__all__ = ["SpadayRegularTable"]


class SpadayRegularTable(Component):
    """Viewport-virtualized table over serializable record rows."""

    tag = "spaday-regular-table"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        columns: Any = None,
        rows: Any = None,
        rowPatch: Any = None,
        streamUrl: str | None = None,
        virtualMode: Literal["both", "horizontal", "vertical", "none"] | None = None,
        rowHeader: str | None = None,
        rowHeight: float | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "columns": columns,
                "rows": rows,
                "rowPatch": rowPatch,
                "streamUrl": streamUrl,
                "virtualMode": virtualMode,
                "rowHeader": rowHeader,
                "rowHeight": rowHeight,
            },
            **props,
        )
